[package]
name = "rust-e2e-encryption-example"
version = "0.1.0"
authors = ["Mario Zupan <mario@zupzup.org>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.6"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
